//! Statistical equivalence tests comparing ferrolearn linear models against
//! scikit-learn reference values stored in `tests/fixtures/sklearn_reference/`.
//!
//! These tests load JSON fixtures generated by `scripts/generate_sklearn_fixtures.py`
//! and verify that ferrolearn produces numerically identical results within
//! tight tolerances.

use ferrolearn_core::introspection::HasCoefficients;
use ferrolearn_core::{Fit, Predict};
use ndarray::{Array1, Array2};

// ---------------------------------------------------------------------------
// JSON helpers
// ---------------------------------------------------------------------------

fn json_to_array2(value: &serde_json::Value) -> Array2<f64> {
    let rows: Vec<Vec<f64>> = value
        .as_array()
        .unwrap()
        .iter()
        .map(|row| {
            row.as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap())
                .collect()
        })
        .collect();
    let n_rows = rows.len();
    let n_cols = rows[0].len();
    let flat: Vec<f64> = rows.into_iter().flatten().collect();
    Array2::from_shape_vec((n_rows, n_cols), flat).unwrap()
}

fn json_to_array1(value: &serde_json::Value) -> Array1<f64> {
    let vec: Vec<f64> = value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    Array1::from_vec(vec)
}

fn json_to_labels(value: &serde_json::Value) -> Array1<usize> {
    let vec: Vec<usize> = value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    Array1::from_vec(vec)
}

/// Assert two f64 slices are element-wise close within relative tolerance.
fn assert_array_close(actual: &[f64], expected: &[f64], epsilon: f64, label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: length mismatch");
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (a - e).abs();
        let denom = e.abs().max(1.0);
        assert!(
            diff / denom <= epsilon,
            "{label}[{i}]: actual={a}, expected={e}, rel_diff={rel}",
            rel = diff / denom,
        );
    }
}

/// Compute R-squared score.
fn r2_score(y_true: &[f64], y_pred: &[f64]) -> f64 {
    let n = y_true.len() as f64;
    let y_mean: f64 = y_true.iter().sum::<f64>() / n;
    let ss_res: f64 = y_true
        .iter()
        .zip(y_pred.iter())
        .map(|(t, p)| (t - p).powi(2))
        .sum();
    let ss_tot: f64 = y_true.iter().map(|t| (t - y_mean).powi(2)).sum();
    1.0 - ss_res / ss_tot
}

// ---------------------------------------------------------------------------
// LinearRegression
// ---------------------------------------------------------------------------

#[test]
fn sklearn_equiv_linear_regression() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/sklearn_reference/linear_regression.json"
    ))
    .unwrap();

    let x = json_to_array2(&fixture["X_train"]);
    let y = json_to_array1(&fixture["y_train"]);
    let x_test = json_to_array2(&fixture["X_test"]);
    let expected_coef = json_to_array1(&fixture["coef"]);
    let expected_intercept = fixture["intercept"].as_f64().unwrap();
    let expected_preds = json_to_array1(&fixture["predictions_train"]);
    let expected_preds_test = json_to_array1(&fixture["predictions_test"]);
    let expected_r2 = fixture["r2_score"].as_f64().unwrap();

    let model = ferrolearn_linear::LinearRegression::<f64>::new().with_fit_intercept(true);
    let fitted = model.fit(&x, &y).unwrap();

    // Coefficients: relative error < 1e-8.
    assert_array_close(
        fitted.coefficients().as_slice().unwrap(),
        expected_coef.as_slice().unwrap(),
        1e-8,
        "LinearRegression coef",
    );

    // Intercept: relative error < 1e-8.
    let diff = (fitted.intercept() - expected_intercept).abs();
    let denom = expected_intercept.abs().max(1.0);
    assert!(
        diff / denom < 1e-8,
        "LinearRegression intercept: actual={}, expected={expected_intercept}",
        fitted.intercept()
    );

    // Training predictions: relative error < 1e-10.
    let preds = fitted.predict(&x).unwrap();
    assert_array_close(
        preds.as_slice().unwrap(),
        expected_preds.as_slice().unwrap(),
        1e-10,
        "LinearRegression predictions_train",
    );

    // Test predictions: relative error < 1e-10.
    let preds_test = fitted.predict(&x_test).unwrap();
    assert_array_close(
        preds_test.as_slice().unwrap(),
        expected_preds_test.as_slice().unwrap(),
        1e-10,
        "LinearRegression predictions_test",
    );

    // R2 score.
    let actual_r2 = r2_score(
        y.as_slice().unwrap(),
        preds.as_slice().unwrap(),
    );
    assert!(
        (actual_r2 - expected_r2).abs() < 1e-10,
        "LinearRegression R2: actual={actual_r2}, expected={expected_r2}"
    );
}

// ---------------------------------------------------------------------------
// LinearRegression single feature
// ---------------------------------------------------------------------------

#[test]
fn sklearn_equiv_linear_regression_single_feature() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/sklearn_reference/linear_regression_single_feature.json"
    ))
    .unwrap();

    let x = json_to_array2(&fixture["X_train"]);
    let y = json_to_array1(&fixture["y_train"]);
    let expected_coef = json_to_array1(&fixture["coef"]);
    let expected_intercept = fixture["intercept"].as_f64().unwrap();
    let expected_preds = json_to_array1(&fixture["predictions_train"]);

    let model = ferrolearn_linear::LinearRegression::<f64>::new().with_fit_intercept(true);
    let fitted = model.fit(&x, &y).unwrap();

    assert_array_close(
        fitted.coefficients().as_slice().unwrap(),
        expected_coef.as_slice().unwrap(),
        1e-8,
        "LinearRegression(1feat) coef",
    );

    let diff = (fitted.intercept() - expected_intercept).abs();
    let denom = expected_intercept.abs().max(1.0);
    assert!(
        diff / denom < 1e-8,
        "LinearRegression(1feat) intercept: actual={}, expected={expected_intercept}",
        fitted.intercept()
    );

    let preds = fitted.predict(&x).unwrap();
    assert_array_close(
        preds.as_slice().unwrap(),
        expected_preds.as_slice().unwrap(),
        1e-10,
        "LinearRegression(1feat) predictions",
    );
}

// ---------------------------------------------------------------------------
// Ridge
// ---------------------------------------------------------------------------

#[test]
fn sklearn_equiv_ridge() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/sklearn_reference/ridge.json"
    ))
    .unwrap();

    let x = json_to_array2(&fixture["X_train"]);
    let y = json_to_array1(&fixture["y_train"]);
    let expected_coef = json_to_array1(&fixture["coef"]);
    let expected_intercept = fixture["intercept"].as_f64().unwrap();
    let expected_preds = json_to_array1(&fixture["predictions_train"]);
    let alpha = fixture["params"]["alpha"].as_f64().unwrap();

    let model = ferrolearn_linear::Ridge::<f64>::new()
        .with_alpha(alpha)
        .with_fit_intercept(true);
    let fitted = model.fit(&x, &y).unwrap();

    assert_array_close(
        fitted.coefficients().as_slice().unwrap(),
        expected_coef.as_slice().unwrap(),
        1e-8,
        "Ridge coef",
    );

    let diff = (fitted.intercept() - expected_intercept).abs();
    let denom = expected_intercept.abs().max(1.0);
    assert!(
        diff / denom < 1e-8,
        "Ridge intercept: actual={}, expected={expected_intercept}",
        fitted.intercept()
    );

    let preds = fitted.predict(&x).unwrap();
    assert_array_close(
        preds.as_slice().unwrap(),
        expected_preds.as_slice().unwrap(),
        1e-10,
        "Ridge predictions",
    );
}

// ---------------------------------------------------------------------------
// Lasso
// ---------------------------------------------------------------------------

#[test]
fn sklearn_equiv_lasso() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/sklearn_reference/lasso.json"
    ))
    .unwrap();

    let x = json_to_array2(&fixture["X_train"]);
    let y = json_to_array1(&fixture["y_train"]);
    let expected_coef = json_to_array1(&fixture["coef"]);
    let expected_intercept = fixture["intercept"].as_f64().unwrap();
    let expected_preds = json_to_array1(&fixture["predictions_train"]);
    let alpha = fixture["params"]["alpha"].as_f64().unwrap();

    let model = ferrolearn_linear::Lasso::<f64>::new()
        .with_alpha(alpha)
        .with_fit_intercept(true)
        .with_max_iter(10_000)
        .with_tol(1e-8);
    let fitted = model.fit(&x, &y).unwrap();

    // Coordinate descent: looser tolerance (1e-3 for coefficients).
    assert_array_close(
        fitted.coefficients().as_slice().unwrap(),
        expected_coef.as_slice().unwrap(),
        1e-3,
        "Lasso coef",
    );

    let diff = (fitted.intercept() - expected_intercept).abs();
    let denom = expected_intercept.abs().max(1.0);
    assert!(
        diff / denom < 1e-3,
        "Lasso intercept: actual={}, expected={expected_intercept}",
        fitted.intercept()
    );

    let preds = fitted.predict(&x).unwrap();
    assert_array_close(
        preds.as_slice().unwrap(),
        expected_preds.as_slice().unwrap(),
        1e-2,
        "Lasso predictions",
    );
}

// ---------------------------------------------------------------------------
// ElasticNet
// ---------------------------------------------------------------------------

#[test]
fn sklearn_equiv_elastic_net() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/sklearn_reference/elastic_net.json"
    ))
    .unwrap();

    let x = json_to_array2(&fixture["X_train"]);
    let y = json_to_array1(&fixture["y_train"]);
    let expected_coef = json_to_array1(&fixture["coef"]);
    let expected_intercept = fixture["intercept"].as_f64().unwrap();
    let expected_preds = json_to_array1(&fixture["predictions_train"]);
    let alpha = fixture["params"]["alpha"].as_f64().unwrap();
    let l1_ratio = fixture["params"]["l1_ratio"].as_f64().unwrap();

    let model = ferrolearn_linear::ElasticNet::<f64>::new()
        .with_alpha(alpha)
        .with_l1_ratio(l1_ratio)
        .with_fit_intercept(true)
        .with_max_iter(10_000)
        .with_tol(1e-8);
    let fitted = model.fit(&x, &y).unwrap();

    // Coordinate descent: moderate tolerance.
    assert_array_close(
        fitted.coefficients().as_slice().unwrap(),
        expected_coef.as_slice().unwrap(),
        1e-3,
        "ElasticNet coef",
    );

    let diff = (fitted.intercept() - expected_intercept).abs();
    let denom = expected_intercept.abs().max(1.0);
    assert!(
        diff / denom < 1e-3,
        "ElasticNet intercept: actual={}, expected={expected_intercept}",
        fitted.intercept()
    );

    let preds = fitted.predict(&x).unwrap();
    assert_array_close(
        preds.as_slice().unwrap(),
        expected_preds.as_slice().unwrap(),
        1e-2,
        "ElasticNet predictions",
    );
}

// ---------------------------------------------------------------------------
// LogisticRegression
// ---------------------------------------------------------------------------

#[test]
fn sklearn_equiv_logistic_regression() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/sklearn_reference/logistic_regression.json"
    ))
    .unwrap();

    let x = json_to_array2(&fixture["X_train"]);
    let y = json_to_labels(&fixture["y_train"]);
    let expected_classes: Vec<usize> = fixture["predicted_classes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let expected_proba = json_to_array2(&fixture["predicted_proba"]);
    let expected_accuracy = fixture["accuracy"].as_f64().unwrap();

    // Use high C (weak regularization) to match sklearn's unregularized solution.
    let model = ferrolearn_linear::LogisticRegression::<f64>::new()
        .with_c(1.0)
        .with_fit_intercept(true)
        .with_max_iter(5000)
        .with_tol(1e-8);
    let fitted = model.fit(&x, &y).unwrap();

    // Predicted classes: match rate >= 90%.
    // Note: ferrolearn uses a different L-BFGS implementation than sklearn,
    // and the regularization path differs slightly, so exact agreement is
    // not expected. A 90% match rate on training data is strong agreement.
    let pred_classes = fitted.predict(&x).unwrap();
    let n_match: usize = pred_classes
        .iter()
        .zip(expected_classes.iter())
        .filter(|(a, b)| a == b)
        .count();
    let match_rate = n_match as f64 / expected_classes.len() as f64;
    assert!(
        match_rate >= 0.90,
        "LogisticRegression class match rate {match_rate:.4} < 0.90 vs sklearn"
    );

    // Accuracy should be close to sklearn's.
    let n_correct: usize = pred_classes
        .iter()
        .zip(y.iter())
        .filter(|(a, b)| a == b)
        .count();
    let accuracy = n_correct as f64 / y.len() as f64;
    assert!(
        (accuracy - expected_accuracy).abs() < 0.05,
        "LogisticRegression accuracy: actual={accuracy:.4}, sklearn={expected_accuracy:.4}"
    );

    // Predicted probabilities: each row sums to 1.
    let pred_proba = fitted.predict_proba(&x).unwrap();
    for i in 0..pred_proba.nrows() {
        let row_sum: f64 = pred_proba.row(i).sum();
        assert!(
            (row_sum - 1.0).abs() < 1e-10,
            "LogisticRegression proba row {i} sum = {row_sum}"
        );
    }

    // Directional agreement on probabilities >= 90%.
    // Different solver implementations may place decision boundaries
    // slightly differently, especially for borderline samples.
    let mut directional_matches = 0usize;
    for i in 0..pred_proba.nrows() {
        let actual_class1 = pred_proba[[i, 1]] > 0.5;
        let expected_class1 = expected_proba[[i, 1]] > 0.5;
        if actual_class1 == expected_class1 {
            directional_matches += 1;
        }
    }
    let dir_acc = directional_matches as f64 / pred_proba.nrows() as f64;
    assert!(
        dir_acc >= 0.90,
        "LogisticRegression directional proba agreement {dir_acc:.4} < 0.90"
    );
}
